management:
  endpoints:
    # Actuator HTTP 配置项，对应 WebEndpointProperties 配置类
    web:
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。

spring:
  application:
    name: demo-application # 应用名
  boot:
    admin:
      client:
        url: http://127.0.0.1:8080 # Spring Boot Admin Server 地址

server:
  port: 18080 # 设置自定义 Server 端口，避免和 Spring Boot Admin Server 端口冲突。
