dubbo:
  scan:
    base-packages: cn.iocoder.springcloudalibaba.labx7.providerdemo.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost

spring:
  application:
    name: demo-provider
#  main:
#    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
